airpollution/urls.py
from django.urls import path
from . import views

app_name = 'airpollution'

urlpatterns = [
    path('', views.airpollution, name='airpollution'),
    path('temp_country_creator/', views.temp_country_creator, name='temp_country_creator'),
    path('temp_add_colors_to_pollutants/', views.temp_add_colors_to_pollutants, name='temp_add_colors_to_pollutants'),
    path('airpollution_table_data/', views.airpollution_table_data, name='airpollution_table_data'),
    path('airpollution_visual_data1/', views.airpollution_visual_data1, name='airpollution_visual_data1'),
    path('airpollution_visual_data2/', views.airpollution_visual_data2, name='airpollution_visual_data2'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('airpollution/', include('airpollution.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.index, name='index'),
]

airpollution/models.py
from django.db import models

# Create your models here.


class Pollutant(models.Model):
    """Pollution model for airpollution app """
    name = models.CharField(max_length=50, primary_key=True)
    limit_value = models.SmallIntegerField(null=True)
    color = models.CharField(max_length=30, default='#000000')
    removed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'pollutants'


class Country(models.Model):
    """Country model for airpollution app """
    iso_code = models.CharField(max_length=3, primary_key=True)
    name = models.CharField(max_length=180, unique=True)
    color = models.CharField(max_length=30, default='#000000')
    removed = models.BooleanField(default=False)
    longitude = models.FloatField(null=True)
    latitude = models.FloatField(null=True)
    altitude = models.FloatField(null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'countries'


class PollutantEntry(models.Model):
    """PollutantEntry model for airpollution app """
    pollutant = models.ForeignKey(
        Pollutant, on_delete=models.CASCADE, related_name='entries')
    country = models.ForeignKey(
        Country, on_delete=models.CASCADE, related_name='entries')
    year = models.IntegerField()
    city = models.CharField(max_length=50, default='', blank=True)
    station_code = models.CharField(max_length=30, default='', blank=True)
    station_name = models.CharField(max_length=100, default='', blank=True)
    pollution_level = models.FloatField()
    units = models.CharField(max_length=50, default='', blank=True)
    station_type = models.CharField(max_length=30, default='', blank=True)
    station_area = models.CharField(max_length=100, default='', blank=True)
    longitude = models.FloatField(null=True)
    latitude = models.FloatField(null=True)
    altitude = models.FloatField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.id} {self.pollutant.name} {self.year}'

    class Meta:
        verbose_name_plural = 'pollutant entries'

airpollution/views.py
from django.http import HttpResponse, JsonResponse
from django.db.models import Q, Sum, Max, Min
from django.shortcuts import render, redirect
from django import forms
import openpyxl
import colorsys
import json

from airpollution.models import Pollutant, Country, PollutantEntry
from airpollution.helpers import get_headers_and_units, XLHEADERS


class ExcelUploadForm(forms.Form):
    year = forms.CharField(max_length=4)
    file = forms.FileField()

# Create your views here.


def airpollution(request):
    ctx = {
        'app_name': request.resolver_match.app_name,
        'pollutant_list': [p.name for p in Pollutant.objects.all()]
    }
    if request.method == 'GET':
        pass
    elif request.method == 'POST':
        form = ExcelUploadForm(request.POST, request.FILES)
        if form.is_valid():
            year = form.cleaned_data['year']
            file = form.cleaned_data['file']
            wb = openpyxl.load_workbook(filename=file, read_only=False)
            tab_names = wb.get_sheet_names()
            for tab_name in tab_names:
                ws = wb[tab_name]
                pollutant_name = tab_name.split('_')[0].strip()
                pollutant = Pollutant.objects.get_or_create(
                    name=pollutant_name)

                if pollutant[0].limit_value is None:
                    limit_value = int(ws['A'][2].value.split()[-2])
                    pollutant[0].limit_value = limit_value
                    pollutant[0].save()
                headers_row, headers, units = get_headers_and_units(ws)

                # Save all entrties to database
                to_insert = []
                for i, row in enumerate(ws.rows):
                    if i <= headers_row:  # Skip to actual entries
                        continue

                    country = row[headers[XLHEADERS.COUNTRY]].value
                    if country is None:
                        break

                    if len(country) > 2:
                        country_object = Country.objects.filter(
                            name=country).first()
                    else:
                        country_object = Country.objects.get(pk=country)

                    city = row[headers[XLHEADERS.CITY]].value
                    station_name = row[headers[XLHEADERS.CITY]].value
                    station_area = row[headers[XLHEADERS.AREA]].value

                    data = {
                        'pollutant': pollutant[0],
                        'country': country_object,
                        'year': year,
                        'city': city if city else '',
                        'station_code': row[headers[XLHEADERS.STATION_EOI_CODE]].value,
                        'station_name': station_name if station_name else '',
                        'pollution_level': row[headers[XLHEADERS.AIR_POLLUTION_LEVEL]].value,
                        'units': units,
                        'station_type': row[headers[XLHEADERS.TYPE]].value,
                        'station_area': station_area if station_area else '',
                        'longitude': row[headers[XLHEADERS.LONGITUDE]].value,
                        'latitude': row[headers[XLHEADERS.LATITUDE]].value,
                        'altitude': row[headers[XLHEADERS.ALTITUDE]].value,
                    }

                    to_insert.append(PollutantEntry(**data))
                    print(to_insert)
                    PollutantEntry.objects.filter(
                        year=year, pollutant=pollutant[0]).delete()
                    PollutantEntry.objects.bulk_create(to_insert)
        ctx['message_sucess'] = 'File uploaded successfully!!'
    else:
        return HttpResponse('This view only handles GET and POST request')
    return render(request, 'airpollution/welcome.html', ctx)


def airpollution_table_data(request):
    table_data = {}

    pollutant_list = [pollutant for pollutant in Pollutant.objects.all()]
    country_list = [country for country in Country.objects.all()]
    for pollutant in pollutant_list:
        table_data[pollutant.name] = {}

        for i, country in enumerate(country_list):
            total = PollutantEntry.objects.aggregate(total=Sum('pollution_level',
                                                               filter=Q(pollutant=pollutant, country=country)))['total']

            minimun = PollutantEntry.objects.aggregate(min=Min('pollution_level',
                                                               filter=Q(pollutant=pollutant, country=country)))['min']

            maximun = PollutantEntry.objects.aggregate(max=Max('pollution_level',
                                                               filter=Q(pollutant=pollutant, country=country)))['max']
            count = PollutantEntry.objects.filter(
                pollutant=pollutant, country=country).count()
            units = PollutantEntry.objects.filter(
                pollutant=pollutant, country=country).first()
            units = units.units if units else ''
            if total is not None and count:
                table_data[pollutant.name][country.iso_code] = {
                    'avg': total / count,
                    'min': minimun,
                    'max': maximun,
                    'limit': pollutant.limit_value,
                    'units': units}

    return JsonResponse(table_data)


def airpollution_visual_data1(request):
    visuals_data = {'Pollutions Levels by Pollutant by Country': {
        'chart_type': 'chart1',
        'labels': [],
        'datasets': [
            {
                'label': 'limit',
                'backgroundColor': '#338DD8',
                'stack': 'limit',
                'data': [],
            }
        ]
    }}
    pollutant_list = [pollutant for pollutant in Pollutant.objects.all()]
    country_list = [country for country in Country.objects.all()]
    visuals_data['Pollutions Levels by Pollutant by Country']['datasets'] += \
        [{'label': c.name, 'backgroundColor': c.color,
            'hidden': 'true', 'data': []} for c in country_list]

    for pollutant in pollutant_list:
        visuals_data['Pollutions Levels by Pollutant by Country']['labels'].append(
            pollutant.name)
        visuals_data['Pollutions Levels by Pollutant by Country']['datasets'][0]['data'].append(
            pollutant.limit_value)
        for i, country in enumerate(country_list):
            total = PollutantEntry.objects.aggregate(total=Sum('pollution_level',
                                                               filter=Q(pollutant=pollutant, country=country)))['total']

            count = PollutantEntry.objects.filter(
                pollutant=pollutant, country=country).count()

            if total is not None and count:
                visuals_data['Pollutions Levels by Pollutant by Country']['datasets'][i +
                                                                                      1]['data'].append(round(total/count, 2))
            else:
                visuals_data['Pollutions Levels by Pollutant by Country']['datasets'][i +
                                                                                      1]['data'].append(-1)

    return JsonResponse(visuals_data)


def airpollution_visual_data2(request):
    pollutant_name = request.GET.get('pollutant', 'PM10')
    pollutant = Pollutant.objects.get(name=pollutant_name)
    sumary_type = request.GET.get('sumary_type', 'max')
    if sumary_type == 'avg':
        name_prefix = 'Average'
    elif sumary_type == 'min':
        name_prefix = 'Mininum'
    else:
        name_prefix = 'Maxinum'
    all_years = [pe['year'] for pe in PollutantEntry.objects.order_by(
        'year').values('year').distinct()]
    all_countries = list(Country.objects.all())
    all_pollutions = [p.name for p in Pollutant.objects.all()]

    visuals_data = {
        'name': f'{name_prefix} pollution level by country over time',
        'labels': all_years,
        'datasets':  [
            {
                'label': 'limit',
                'backgroundColor': '#338DD8',
                'borderColor': '#338DD8',
                'data': [pollutant.limit_value] * len(all_years),
                'fill': False
            }
        ]
    }

    for country in all_countries:
        country_data = {
            'label': country.name,
            'backgroundColor': country.color,
            'borderColor': country.color,
            'data': [],
            'fill': False,
            'hidden': True
        }

        visuals_data['datasets'].append(country_data)

        for year in all_years:
            f = Q(pollutant=pollutant, year=year, country=country)

            if sumary_type == 'avg':
                country_tot = PollutantEntry.objects.aggregate(s=Sum('pollution_level', filter=f))['s']
                country_count = PollutantEntry.objects.filter(f).count()
                country_data['data'].append(country_tot / country_count if country_count else 0)
            elif sumary_type == 'min':
                country_min = PollutantEntry.objects.aggregate(s=Min('pollution_level', filter=f))['s']
                country_data['data'].append(country_min if country_min else 0)
            else: # by default -> max
                country_max = PollutantEntry.objects.aggregate(s=Min('pollution_level', filter=f))['s']
                country_data['data'].append(country_max if country_max else 0)



    return JsonResponse(visuals_data)


# def airpollution_backup(request):
#     if request.method == 'GET':
#         table_data = {}
#         visuals_data = {'Pollutions Levels by Pollutant by Country': {
#             'chart_type': 'chart1',
#             'labels': [],
#             'datasets': [
#                 {
#                     'label': 'limit',
#                     'backgroundColor': '#338DD8',
#                     'stack': 'limit',
#                     'data': [],
#                 }
#             ]
#         }}

templates/airpollution/welcome.html
{% extends 'base.html' %} {% block content %}
<!-- Upload file Section-->
<section class="page-section mt-5" id="import-form">
  <div class="container">
    <!--Heading-->
    <h2
      class="page-section-heading text-center text-uppercase text-secondary mb-0"
    >
      Upload File
    </h2>
    <!-- Icon Divider-->
    <div class="divider-custom">
      <div class="divider-custom-line"></div>
      <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
      <div class="divider-custom-line"></div>
    </div>
    <!-- Upload Section Form-->
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <form
          id="upload-file"
          name="upload-file"
          enctype="multipart/form-data"
          method="POST"
          action="{% url 'airpollution:airpollution' %}"
        >
          {% csrf_token %}
          <div class="control-group">
            <div
              class="form-group floating-label-form-group controls mb-0 pb-2"
            >
              <label>Year</label>
              <input
                class="form-control"
                id="year"
                name="year"
                type="number"
                placeholder="Year"
                required="required"
                data-validation-required-message=""
              />
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div
              class="form-group floating-label-form-group controls mb-0 pb-2"
            >
              <label>File</label>
              <input
                class="form-control"
                id="file"
                name="file"
                type="file"
                required="required"
                data-validation-required-message=""
              />
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <br />
          <div id="success">{{message_sucess}}</div>
          <div class="form-group">
            <button class="btn btn-primary btn-xl" id="upload" type="submit">
              Upload
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

<!-- Table Section-->
<section class="page-section mt-3" id="data-table">
  <div class="container">
    <!--Heading-->
    <h2
      class="page-section-heading text-center text-uppercase text-secondary mb-0"
    >
      Data table
    </h2>
    <!-- Icon Divider-->
    <div class="divider-custom">
      <div class="divider-custom-line"></div>
      <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
      <div class="divider-custom-line"></div>
    </div>
    <!-- Table-->
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <table id="our-table" class="table">
          <thead>
            <tr>
              <th scope="col">Pollutant</th>
              <th scope="col">Country</th>
              <th scope="col">Avg</th>
              <th scope="col">Min</th>
              <th scope="col">Max</th>
              <th scope="col">Limit</th>
              <th scope="col">Units</th>
            </tr>
          </thead>
          <tbody id="table-body"></tbody>
        </table>
      </div>
    </div>
  </div>
</section>

<!-- Visuals Section-->
<section class="page-section mt-3" id="data-visuals">
  <div class="container">
    <!--Heading-->
    <h2
      class="page-section-heading text-center text-uppercase text-secondary mb-0"
    >
      Data visuals
    </h2>
    <!-- Icon Divider-->
    <div class="divider-custom">
      <div class="divider-custom-line"></div>
      <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
      <div class="divider-custom-line"></div>
    </div>
    <!-- Visuas-->
    <div class="row">
      <div id="visual-container" class="col-lg-8 mx-auto">
        <div class="row">
          <div class="col-12 col-md-6">
            <select class="form-control" id="chart2-summary-type">
              <option value="max">Maximun</option>
              <option value="min">Minimun</option>
              <option value="avg">Average</option>
            </select>
          </div>
          <div class="col-12 col-md-6">
            <select class="form-control" id="chart2-pollutant">
              {% for pollutant in pollutant_list  %}
                <option value={{pollutant}}>{{pollutant}}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <div id="chart2">

        </div>

      </div>
    </div>
  </div>
</section>

{% endblock %} {% block js %}
<script>
  function renderChart(chart_type, canvas, name, labels, datasets) {
    let scales = {};

    if (chart_type === "bar") {
      scales = {
        xAxes: [
          {
            stacked: true,
          },
        ],
        yAxes: [
          {
            stacked: true,
          },
        ],
      };
    } else if (chart_type === "line") {
      scales = {
        xAxes: [
          {
            display: true,
            scaleLabel: {
              display: true,
              labelString: "Mount",
            },
          },
        ],
        yAxes: [
          {
            display: true,
            scaleLabel: {
              display: true,
              labelString: "Value",
            },
          },
        ],
      };
    }
    myChart = new Chart(canvas, {
      type: chart_type,
      data: { labels: labels, datasets: datasets },
      options: {
        title: {
          display: true,
          text: name,
        },
        tooltips: {
          mode: "index",
          intersect: false,
          position: "nearest",
        },
        responsive: true,
        scales: scales,
      },
    });
  }

  $(document).ready(function () {
    $.get("airpollution_table_data", function (data) {
      //console.log(data)
      for (const [pollution_name, pollution_data] of Object.entries(data)) {
        for (const [country_iso, d] of Object.entries(pollution_data)) {
          let tr = $("<tr />");
          tr.append($("<th />", { text: pollution_name }));
          tr.append($("<td />", { text: country_iso }));
          tr.append($("<td />", { text: d.avg.toFixed(2) }));
          tr.append($("<td />", { text: d.min.toFixed(2) }));
          tr.append($("<td />", { text: d.max.toFixed(2) }));
          tr.append($("<td />", { text: d.limit }));
          tr.append($("<td />", { text: d.units }));
          $("#table-body").append(tr);
        }
      }
      $("#our-table").DataTable();
    });

    $.get("airpollution_visual_data1", function (data) {
      //console.log(data);
      for (const [chart_name, d] of Object.entries(data)) {
        let canvas = $("<canvas />")
          .addClass("mb-3")
          .attr("width", "400")
          .attr("height", "350");
        $("#visual-container").append(canvas);
        renderChart("bar", canvas, chart_name, d.labels, d.datasets);
      }
    });

    let loadChart2 = function (summary_type, pollutans) {
      $.get(`airpollution_visual_data2?summary_types=${summary_type}&pollutant=${pollutans}`, function (data) {
        //console.log(data);
        let canvas = $("<canvas />")
          .addClass("mb-3")
          .attr("width", "400")
          .attr("height", "350");
        $("#chart2").html(canvas);
        renderChart("line", canvas, data.name, data.labels, data.datasets);
      });
    };

    loadChart2('max', 'PM10')
    $("#chart2-summary-type", "#chart2-pollutant").on('change', function(){
      let summary_type = $('chart2-summary-type').val()
      let pollutant = $('chart2-pollutant').val()
      loadChart2(summary_type, pollutant)
    })

  });
</script>
{% endblock %}